pipelines:
    default:
        - step:
            name: "Initialization of the repository"
            image: simplinion/swagger-codegen:1.0.46
            trigger: automatic
            script:
                - ./initialize.sh
    tags:
        V.*:
            - step:
                name: Publishing of new version
                image: simplinion/swagger-codegen:1.0.46
                trigger: automatic
                script:
                    - ./publish.sh -v="${BITBUCKET_TAG/V./}"
                artifacts:
                    - artifacts/**
