pipelines:
    default:
        - step:
            name: "Initialization of the repository"
            image: chocotechnologies/swagger-codegen:1.0.28
            trigger: automatic
            script:
                - ./initialize.sh
    tags:
        V.*:
            - step:
                name: Publishing of new version
                image: chocotechnologies/swagger-codegen:1.0.28
                trigger: automatic
                script:
                    - git config --global user.email "pipeline@choco-technologies.com"
                    - git config --global user.name "auth-gen pipelines"
                    - ./initialize.sh
                    - ./publish.sh -v="${BITBUCKET_TAG/V./}"
