/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthTokenRequest.h
 *
 * 
 */

#ifndef ChocoAuthTokenRequest_H_
#define ChocoAuthTokenRequest_H_

#include <QJsonObject>


#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthTokenRequest: public ChocoAuthObject {
public:
    ChocoAuthTokenRequest();
    ChocoAuthTokenRequest(QString json);
    ~ChocoAuthTokenRequest();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthTokenRequest* fromJson(QString jsonString) override;

    QString* getGrantType();
    void setGrantType(QString* grant_type);

    QString* getClientId();
    void setClientId(QString* client_id);

    QString* getClientSecret();
    void setClientSecret(QString* client_secret);

    QString* getRedirectUri();
    void setRedirectUri(QString* redirect_uri);

    QString* getCode();
    void setCode(QString* code);


    virtual bool isSet() override;

private:
    QString* grant_type;
    bool m_grant_type_isSet;

    QString* client_id;
    bool m_client_id_isSet;

    QString* client_secret;
    bool m_client_secret_isSet;

    QString* redirect_uri;
    bool m_redirect_uri_isSet;

    QString* code;
    bool m_code_isSet;

};

}

#endif /* ChocoAuthTokenRequest_H_ */
