/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ChocoAuthClientApi.h"
#include "ChocoAuthHelpers.h"
#include "ChocoAuthModelFactory.h"
#include "ChocoAuthQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace ChocoAuth {

ChocoAuthClientApi::ChocoAuthClientApi() {}

ChocoAuthClientApi::~ChocoAuthClientApi() {}

ChocoAuthClientApi::ChocoAuthClientApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
ChocoAuthClientApi::createClient(QString* user_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/create/client/{userId}");

    QString user_idPathParam("{"); user_idPathParam.append("userId").append("}");
    fullPath.replace(user_idPathParam, stringValue(user_id));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "PUT");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthClientApi::createClientCallback);

    worker->execute(&input);
}

void
ChocoAuthClientApi::createClientCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthClientInfo* output = static_cast<ChocoAuthClientInfo*>(create(json, QString("ChocoAuthClientInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthClientInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit createClientSignal(output);
    } else {
        emit createClientSignalE(output, error_type, error_str);
        emit createClientSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthClientApi::deleteClient(QString* client_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/client/{clientId}");

    QString client_idPathParam("{"); client_idPathParam.append("clientId").append("}");
    fullPath.replace(client_idPathParam, stringValue(client_id));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "DELETE");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthClientApi::deleteClientCallback);

    worker->execute(&input);
}

void
ChocoAuthClientApi::deleteClientCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit deleteClientSignal();
    } else {
        emit deleteClientSignalE(error_type, error_str);
        emit deleteClientSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthClientApi::getClient(QString* client_id) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/client/{clientId}");

    QString client_idPathParam("{"); client_idPathParam.append("clientId").append("}");
    fullPath.replace(client_idPathParam, stringValue(client_id));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthClientApi::getClientCallback);

    worker->execute(&input);
}

void
ChocoAuthClientApi::getClientCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthClientInfo* output = static_cast<ChocoAuthClientInfo*>(create(json, QString("ChocoAuthClientInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthClientInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getClientSignal(output);
    } else {
        emit getClientSignalE(output, error_type, error_str);
        emit getClientSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthClientApi::getClients() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/clients");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthClientApi::getClientsCallback);

    worker->execute(&input);
}

void
ChocoAuthClientApi::getClientsCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QList<ChocoAuthClientInfo*>* output = new QList<ChocoAuthClientInfo*>();
    QString json(worker->response);
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonArray jsonArray = doc.array();
    auto wrapper = new ChocoAuthQObjectWrapper<QList<ChocoAuthClientInfo*>*> (output);
    wrapper->deleteLater();
    foreach(QJsonValue obj, jsonArray) {
        ChocoAuthClientInfo* o = new ChocoAuthClientInfo();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        auto objwrapper = new ChocoAuthQObjectWrapper<ChocoAuthClientInfo*> (o);
        objwrapper->deleteLater();
        output->append(o);
    }
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getClientsSignal(output);
    } else {
        emit getClientsSignalE(output, error_type, error_str);
        emit getClientsSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthClientApi::updateClient(QString* client_id, ChocoAuthClientInfo& client) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/client/{clientId}");

    QString client_idPathParam("{"); client_idPathParam.append("clientId").append("}");
    fullPath.replace(client_idPathParam, stringValue(client_id));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");


    
    QString output = client.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthClientApi::updateClientCallback);

    worker->execute(&input);
}

void
ChocoAuthClientApi::updateClientCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit updateClientSignal();
    } else {
        emit updateClientSignalE(error_type, error_str);
        emit updateClientSignalEFull(worker, error_type, error_str);
    }
}


}
