/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthClientApi_H_
#define _ChocoAuth_ChocoAuthClientApi_H_

#include "ChocoAuthHttpRequest.h"

#include "ChocoAuthClientInfo.h"
#include "ChocoAuthErrorResponse.h"
#include <QString>

#include <QObject>

namespace ChocoAuth {

class ChocoAuthClientApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthClientApi();
    ChocoAuthClientApi(QString host, QString basePath);
    ~ChocoAuthClientApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void createClient(QString* user_id);
    void deleteClient(QString* client_id);
    void getClient(QString* client_id);
    void getClients();
    void updateClient(QString* client_id, ChocoAuthClientInfo& client);
    
private:
    void createClientCallback (ChocoAuthHttpRequestWorker * worker);
    void deleteClientCallback (ChocoAuthHttpRequestWorker * worker);
    void getClientCallback (ChocoAuthHttpRequestWorker * worker);
    void getClientsCallback (ChocoAuthHttpRequestWorker * worker);
    void updateClientCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void createClientSignal(ChocoAuthClientInfo* summary);
    void deleteClientSignal();
    void getClientSignal(ChocoAuthClientInfo* summary);
    void getClientsSignal(QList<ChocoAuthClientInfo*>* summary);
    void updateClientSignal();
    
    void createClientSignalE(ChocoAuthClientInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void deleteClientSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    void getClientSignalE(ChocoAuthClientInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getClientsSignalE(QList<ChocoAuthClientInfo*>* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void updateClientSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    
    void createClientSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void deleteClientSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getClientSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getClientsSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void updateClientSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
