/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthAuthenticationCode.h
 *
 * Stores information returned in the valid response of &#x60;/login/oauth/authorize&#x60; endpoint 
 */

#ifndef ChocoAuthAuthenticationCode_H_
#define ChocoAuthAuthenticationCode_H_

#include <QJsonObject>


#include <QDateTime>
#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthAuthenticationCode: public ChocoAuthObject {
public:
    ChocoAuthAuthenticationCode();
    ChocoAuthAuthenticationCode(QString json);
    ~ChocoAuthAuthenticationCode();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthAuthenticationCode* fromJson(QString jsonString) override;

    QString* getCode();
    void setCode(QString* code);

    QString* getState();
    void setState(QString* state);

    QString* getRedirectUri();
    void setRedirectUri(QString* redirect_uri);

    QDateTime* getExpirationDate();
    void setExpirationDate(QDateTime* expiration_date);


    virtual bool isSet() override;

private:
    QString* code;
    bool m_code_isSet;

    QString* state;
    bool m_state_isSet;

    QString* redirect_uri;
    bool m_redirect_uri_isSet;

    QDateTime* expiration_date;
    bool m_expiration_date_isSet;

};

}

#endif /* ChocoAuthAuthenticationCode_H_ */
