/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthSignInfo.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthSignInfo::ChocoAuthSignInfo(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthSignInfo::ChocoAuthSignInfo() {
    init();
}

ChocoAuthSignInfo::~ChocoAuthSignInfo() {
    this->cleanup();
}

void
ChocoAuthSignInfo::init() {
    email = new QString("");
    m_email_isSet = false;
    password = new QString("");
    m_password_isSet = false;
}

void
ChocoAuthSignInfo::cleanup() {
    if(email != nullptr) { 
        delete email;
    }
    if(password != nullptr) { 
        delete password;
    }
}

ChocoAuthSignInfo*
ChocoAuthSignInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthSignInfo::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&email, pJson["email"], "QString", "QString");
    
    ::ChocoAuth::setValue(&password, pJson["password"], "QString", "QString");
    
}

QString
ChocoAuthSignInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthSignInfo::asJsonObject() {
    QJsonObject obj;
    if(email != nullptr && *email != QString("")){
        toJsonValue(QString("email"), email, obj, QString("QString"));
    }
    if(password != nullptr && *password != QString("")){
        toJsonValue(QString("password"), password, obj, QString("QString"));
    }

    return obj;
}

QString*
ChocoAuthSignInfo::getEmail() {
    return email;
}
void
ChocoAuthSignInfo::setEmail(QString* email) {
    this->email = email;
    this->m_email_isSet = true;
}

QString*
ChocoAuthSignInfo::getPassword() {
    return password;
}
void
ChocoAuthSignInfo::setPassword(QString* password) {
    this->password = password;
    this->m_password_isSet = true;
}


bool
ChocoAuthSignInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(email != nullptr && *email != QString("")){ isObjectUpdated = true; break;}
        if(password != nullptr && *password != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

