/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthAuthenticationCode.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthAuthenticationCode::ChocoAuthAuthenticationCode(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthAuthenticationCode::ChocoAuthAuthenticationCode() {
    init();
}

ChocoAuthAuthenticationCode::~ChocoAuthAuthenticationCode() {
    this->cleanup();
}

void
ChocoAuthAuthenticationCode::init() {
    code = new QString("");
    m_code_isSet = false;
    state = new QString("");
    m_state_isSet = false;
    redirect_uri = new QString("");
    m_redirect_uri_isSet = false;
    expiration_date = NULL;
    m_expiration_date_isSet = false;
}

void
ChocoAuthAuthenticationCode::cleanup() {
    if(code != nullptr) { 
        delete code;
    }
    if(state != nullptr) { 
        delete state;
    }
    if(redirect_uri != nullptr) { 
        delete redirect_uri;
    }
    if(expiration_date != nullptr) { 
        delete expiration_date;
    }
}

ChocoAuthAuthenticationCode*
ChocoAuthAuthenticationCode::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthAuthenticationCode::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&code, pJson["code"], "QString", "QString");
    
    ::ChocoAuth::setValue(&state, pJson["state"], "QString", "QString");
    
    ::ChocoAuth::setValue(&redirect_uri, pJson["redirect_uri"], "QString", "QString");
    
    ::ChocoAuth::setValue(&expiration_date, pJson["expirationDate"], "QDateTime", "QDateTime");
    
}

QString
ChocoAuthAuthenticationCode::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthAuthenticationCode::asJsonObject() {
    QJsonObject obj;
    if(code != nullptr && *code != QString("")){
        toJsonValue(QString("code"), code, obj, QString("QString"));
    }
    if(state != nullptr && *state != QString("")){
        toJsonValue(QString("state"), state, obj, QString("QString"));
    }
    if(redirect_uri != nullptr && *redirect_uri != QString("")){
        toJsonValue(QString("redirect_uri"), redirect_uri, obj, QString("QString"));
    }
    if(expiration_date != nullptr) { 
        toJsonValue(QString("expirationDate"), expiration_date, obj, QString("QDateTime"));
    }

    return obj;
}

QString*
ChocoAuthAuthenticationCode::getCode() {
    return code;
}
void
ChocoAuthAuthenticationCode::setCode(QString* code) {
    this->code = code;
    this->m_code_isSet = true;
}

QString*
ChocoAuthAuthenticationCode::getState() {
    return state;
}
void
ChocoAuthAuthenticationCode::setState(QString* state) {
    this->state = state;
    this->m_state_isSet = true;
}

QString*
ChocoAuthAuthenticationCode::getRedirectUri() {
    return redirect_uri;
}
void
ChocoAuthAuthenticationCode::setRedirectUri(QString* redirect_uri) {
    this->redirect_uri = redirect_uri;
    this->m_redirect_uri_isSet = true;
}

QDateTime*
ChocoAuthAuthenticationCode::getExpirationDate() {
    return expiration_date;
}
void
ChocoAuthAuthenticationCode::setExpirationDate(QDateTime* expiration_date) {
    this->expiration_date = expiration_date;
    this->m_expiration_date_isSet = true;
}


bool
ChocoAuthAuthenticationCode::isSet(){
    bool isObjectUpdated = false;
    do{
        if(code != nullptr && *code != QString("")){ isObjectUpdated = true; break;}
        if(state != nullptr && *state != QString("")){ isObjectUpdated = true; break;}
        if(redirect_uri != nullptr && *redirect_uri != QString("")){ isObjectUpdated = true; break;}
        
    }while(false);
    return isObjectUpdated;
}
}

