/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthOauthApi_H_
#define _ChocoAuth_ChocoAuthOauthApi_H_

#include "ChocoAuthHttpRequest.h"

#include "ChocoAuthAccessToken.h"
#include "ChocoAuthAuthenticationCode.h"
#include "ChocoAuthAuthorizeRequest.h"
#include "ChocoAuthErrorResponse.h"
#include "ChocoAuthTokenRequest.h"
#include <QString>

#include <QObject>

namespace ChocoAuth {

class ChocoAuthOauthApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthOauthApi();
    ChocoAuthOauthApi(QString host, QString basePath);
    ~ChocoAuthOauthApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void getAccessToken(ChocoAuthTokenRequest& token_request);
    void getAuthenticationCode(ChocoAuthAuthorizeRequest& authorize_request, QString* sign_info);
    
private:
    void getAccessTokenCallback (ChocoAuthHttpRequestWorker * worker);
    void getAuthenticationCodeCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void getAccessTokenSignal(ChocoAuthAccessToken* summary);
    void getAuthenticationCodeSignal(ChocoAuthAuthenticationCode* summary);
    
    void getAccessTokenSignalE(ChocoAuthAccessToken* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getAuthenticationCodeSignalE(ChocoAuthAuthenticationCode* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void getAccessTokenSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getAuthenticationCodeSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
