/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthTokenRequest.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthTokenRequest::ChocoAuthTokenRequest(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthTokenRequest::ChocoAuthTokenRequest() {
    init();
}

ChocoAuthTokenRequest::~ChocoAuthTokenRequest() {
    this->cleanup();
}

void
ChocoAuthTokenRequest::init() {
    grant_type = new QString("");
    m_grant_type_isSet = false;
    client_id = new QString("");
    m_client_id_isSet = false;
    client_secret = new QString("");
    m_client_secret_isSet = false;
    redirect_uri = new QString("");
    m_redirect_uri_isSet = false;
    code = new QString("");
    m_code_isSet = false;
}

void
ChocoAuthTokenRequest::cleanup() {
    if(grant_type != nullptr) { 
        delete grant_type;
    }
    if(client_id != nullptr) { 
        delete client_id;
    }
    if(client_secret != nullptr) { 
        delete client_secret;
    }
    if(redirect_uri != nullptr) { 
        delete redirect_uri;
    }
    if(code != nullptr) { 
        delete code;
    }
}

ChocoAuthTokenRequest*
ChocoAuthTokenRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthTokenRequest::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&grant_type, pJson["grant_type"], "QString", "QString");
    
    ::ChocoAuth::setValue(&client_id, pJson["clientId"], "QString", "QString");
    
    ::ChocoAuth::setValue(&client_secret, pJson["client_secret"], "QString", "QString");
    
    ::ChocoAuth::setValue(&redirect_uri, pJson["redirect_uri"], "QString", "QString");
    
    ::ChocoAuth::setValue(&code, pJson["code"], "QString", "QString");
    
}

QString
ChocoAuthTokenRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthTokenRequest::asJsonObject() {
    QJsonObject obj;
    if(grant_type != nullptr && *grant_type != QString("")){
        toJsonValue(QString("grant_type"), grant_type, obj, QString("QString"));
    }
    if(client_id != nullptr && *client_id != QString("")){
        toJsonValue(QString("clientId"), client_id, obj, QString("QString"));
    }
    if(client_secret != nullptr && *client_secret != QString("")){
        toJsonValue(QString("client_secret"), client_secret, obj, QString("QString"));
    }
    if(redirect_uri != nullptr && *redirect_uri != QString("")){
        toJsonValue(QString("redirect_uri"), redirect_uri, obj, QString("QString"));
    }
    if(code != nullptr && *code != QString("")){
        toJsonValue(QString("code"), code, obj, QString("QString"));
    }

    return obj;
}

QString*
ChocoAuthTokenRequest::getGrantType() {
    return grant_type;
}
void
ChocoAuthTokenRequest::setGrantType(QString* grant_type) {
    this->grant_type = grant_type;
    this->m_grant_type_isSet = true;
}

QString*
ChocoAuthTokenRequest::getClientId() {
    return client_id;
}
void
ChocoAuthTokenRequest::setClientId(QString* client_id) {
    this->client_id = client_id;
    this->m_client_id_isSet = true;
}

QString*
ChocoAuthTokenRequest::getClientSecret() {
    return client_secret;
}
void
ChocoAuthTokenRequest::setClientSecret(QString* client_secret) {
    this->client_secret = client_secret;
    this->m_client_secret_isSet = true;
}

QString*
ChocoAuthTokenRequest::getRedirectUri() {
    return redirect_uri;
}
void
ChocoAuthTokenRequest::setRedirectUri(QString* redirect_uri) {
    this->redirect_uri = redirect_uri;
    this->m_redirect_uri_isSet = true;
}

QString*
ChocoAuthTokenRequest::getCode() {
    return code;
}
void
ChocoAuthTokenRequest::setCode(QString* code) {
    this->code = code;
    this->m_code_isSet = true;
}


bool
ChocoAuthTokenRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(grant_type != nullptr && *grant_type != QString("")){ isObjectUpdated = true; break;}
        if(client_id != nullptr && *client_id != QString("")){ isObjectUpdated = true; break;}
        if(client_secret != nullptr && *client_secret != QString("")){ isObjectUpdated = true; break;}
        if(redirect_uri != nullptr && *redirect_uri != QString("")){ isObjectUpdated = true; break;}
        if(code != nullptr && *code != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

