/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthUserApi_H_
#define _ChocoAuth_ChocoAuthUserApi_H_

#include "ChocoAuthHttpRequest.h"

#include "ChocoAuthErrorResponse.h"
#include "ChocoAuthUserInfo.h"
#include <QString>

#include <QObject>

namespace ChocoAuth {

class ChocoAuthUserApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthUserApi();
    ChocoAuthUserApi(QString host, QString basePath);
    ~ChocoAuthUserApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void getUser(QString* userid);
    void getUsers(qint32 max, qint32 page);
    
private:
    void getUserCallback (ChocoAuthHttpRequestWorker * worker);
    void getUsersCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void getUserSignal(ChocoAuthUserInfo* summary);
    void getUsersSignal(QList<ChocoAuthUserInfo*>* summary);
    
    void getUserSignalE(ChocoAuthUserInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getUsersSignalE(QList<ChocoAuthUserInfo*>* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void getUserSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getUsersSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
