/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthUserInfo.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthUserInfo::ChocoAuthUserInfo(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthUserInfo::ChocoAuthUserInfo() {
    init();
}

ChocoAuthUserInfo::~ChocoAuthUserInfo() {
    this->cleanup();
}

void
ChocoAuthUserInfo::init() {
    user_id = new QString("");
    m_user_id_isSet = false;
    email = new QString("");
    m_email_isSet = false;
    verification = new QList<VerificationEnum*>();
    m_verification_isSet = false;
}

void
ChocoAuthUserInfo::cleanup() {
    if(user_id != nullptr) { 
        delete user_id;
    }
    if(email != nullptr) { 
        delete email;
    }
    if(verification != nullptr) { 
        auto arr = verification;
        for(auto o: *arr) { 
            delete o;
        }
        delete verification;
    }
}

ChocoAuthUserInfo*
ChocoAuthUserInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthUserInfo::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&user_id, pJson["user_id"], "QString", "QString");
    
    ::ChocoAuth::setValue(&email, pJson["email"], "QString", "QString");
    
    
    ::ChocoAuth::setValue(&verification, pJson["verification"], "QList", "QString");
}

QString
ChocoAuthUserInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthUserInfo::asJsonObject() {
    QJsonObject obj;
    if(user_id != nullptr && *user_id != QString("")){
        toJsonValue(QString("user_id"), user_id, obj, QString("QString"));
    }
    if(email != nullptr && *email != QString("")){
        toJsonValue(QString("email"), email, obj, QString("QString"));
    }
    if(verification->size() > 0){
        toJsonArray((QList<void*>*)verification, obj, "verification", "QString");
    }

    return obj;
}

QString*
ChocoAuthUserInfo::getUserId() {
    return user_id;
}
void
ChocoAuthUserInfo::setUserId(QString* user_id) {
    this->user_id = user_id;
    this->m_user_id_isSet = true;
}

QString*
ChocoAuthUserInfo::getEmail() {
    return email;
}
void
ChocoAuthUserInfo::setEmail(QString* email) {
    this->email = email;
    this->m_email_isSet = true;
}

QList<QString*>*
ChocoAuthUserInfo::getVerification() {
    return verification;
}
void
ChocoAuthUserInfo::setVerification(QList<QString*>* verification) {
    this->verification = verification;
    this->m_verification_isSet = true;
}


bool
ChocoAuthUserInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(user_id != nullptr && *user_id != QString("")){ isObjectUpdated = true; break;}
        if(email != nullptr && *email != QString("")){ isObjectUpdated = true; break;}
        if(verification->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

