/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthLoginApi_H_
#define _ChocoAuth_ChocoAuthLoginApi_H_

#include "ChocoAuthHttpRequest.h"

#include "ChocoAuthErrorResponse.h"
#include "ChocoAuthSignInfo.h"
#include "ChocoAuthUserInfo.h"
#include <QString>

#include <QObject>

namespace ChocoAuth {

class ChocoAuthLoginApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthLoginApi();
    ChocoAuthLoginApi(QString host, QString basePath);
    ~ChocoAuthLoginApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void signDown(QString* sign_info);
    void signIn(QString* sign_info);
    void signUp(QString* sign_info);
    
private:
    void signDownCallback (ChocoAuthHttpRequestWorker * worker);
    void signInCallback (ChocoAuthHttpRequestWorker * worker);
    void signUpCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void signDownSignal();
    void signInSignal(ChocoAuthUserInfo* summary);
    void signUpSignal(ChocoAuthSignInfo* summary);
    
    void signDownSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    void signInSignalE(ChocoAuthUserInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void signUpSignalE(ChocoAuthSignInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void signDownSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void signInSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void signUpSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
