/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ChocoAuthOauthApi.h"
#include "ChocoAuthHelpers.h"
#include "ChocoAuthModelFactory.h"
#include "ChocoAuthQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace ChocoAuth {

ChocoAuthOauthApi::ChocoAuthOauthApi() {}

ChocoAuthOauthApi::~ChocoAuthOauthApi() {}

ChocoAuthOauthApi::ChocoAuthOauthApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
ChocoAuthOauthApi::getAccessToken(ChocoAuthTokenRequest& token_request) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/login/oauth/access_token");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");


    
    QString output = token_request.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthOauthApi::getAccessTokenCallback);

    worker->execute(&input);
}

void
ChocoAuthOauthApi::getAccessTokenCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthAccessToken* output = static_cast<ChocoAuthAccessToken*>(create(json, QString("ChocoAuthAccessToken")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthAccessToken*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getAccessTokenSignal(output);
    } else {
        emit getAccessTokenSignalE(output, error_type, error_str);
        emit getAccessTokenSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthOauthApi::getAuthenticationCode(ChocoAuthAuthorizeRequest& authorize_request, QString* sign_info) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/login/oauth/authorize");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "GET");


    
    QString output = authorize_request.asJson();
    input.request_body.append(output);
    

    if (sign_info != nullptr) {
        input.headers.insert("SignInfo", "sign_info");
    }

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthOauthApi::getAuthenticationCodeCallback);

    worker->execute(&input);
}

void
ChocoAuthOauthApi::getAuthenticationCodeCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthAuthenticationCode* output = static_cast<ChocoAuthAuthenticationCode*>(create(json, QString("ChocoAuthAuthenticationCode")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthAuthenticationCode*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getAuthenticationCodeSignal(output);
    } else {
        emit getAuthenticationCodeSignalE(output, error_type, error_str);
        emit getAuthenticationCodeSignalEFull(worker, error_type, error_str);
    }
}


}
