/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_OBJECT_H_
#define _ChocoAuth_OBJECT_H_

#include <QJsonObject>

namespace ChocoAuth {

class ChocoAuthObject {
  public:
    virtual QJsonObject asJsonObject() {
      return QJsonObject();
    }
    virtual ~ChocoAuthObject() {}
    virtual ChocoAuthObject* fromJson(QString jsonString) {
        Q_UNUSED(jsonString);
        return new ChocoAuthObject();
    }
    virtual void fromJsonObject(QJsonObject json) {
        Q_UNUSED(json);
    }
    virtual QString asJson() {
        return QString("");
    }
    virtual bool isSet() {
        return false;
    }
};

}

#endif /* _ChocoAuth_OBJECT_H_ */
