/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef ModelFactory_H_
#define ModelFactory_H_

#include "ChocoAuthObject.h"

#include "ChocoAuthAccessToken.h"
#include "ChocoAuthAuthenticationCode.h"
#include "ChocoAuthAuthorizeRequest.h"
#include "ChocoAuthClientInfo.h"
#include "ChocoAuthErrorResponse.h"
#include "ChocoAuthSignInfo.h"
#include "ChocoAuthTokenRequest.h"
#include "ChocoAuthUserInfo.h"

namespace ChocoAuth {

  inline void* create(QString type) {
    if(QString("ChocoAuthAccessToken").compare(type) == 0) {
      return new ChocoAuthAccessToken();
    }
    if(QString("ChocoAuthAuthenticationCode").compare(type) == 0) {
      return new ChocoAuthAuthenticationCode();
    }
    if(QString("ChocoAuthAuthorizeRequest").compare(type) == 0) {
      return new ChocoAuthAuthorizeRequest();
    }
    if(QString("ChocoAuthClientInfo").compare(type) == 0) {
      return new ChocoAuthClientInfo();
    }
    if(QString("ChocoAuthErrorResponse").compare(type) == 0) {
      return new ChocoAuthErrorResponse();
    }
    if(QString("ChocoAuthSignInfo").compare(type) == 0) {
      return new ChocoAuthSignInfo();
    }
    if(QString("ChocoAuthTokenRequest").compare(type) == 0) {
      return new ChocoAuthTokenRequest();
    }
    if(QString("ChocoAuthUserInfo").compare(type) == 0) {
      return new ChocoAuthUserInfo();
    }
    
    return nullptr;
  }

  inline void* create(QString json, QString type) {
    if(type.startsWith("QString")) {
      return new QString();
    }    
    auto val = static_cast<ChocoAuthObject*>(create(type));
    if(val != nullptr) {
      return val->fromJson(json);
    }
    return nullptr;
  }

}

#endif /* ModelFactory_H_ */
