/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef ChocoAuth_QOBJECT_WRAPPER_H
#define ChocoAuth_QOBJECT_WRAPPER_H

#include <QObject>

namespace ChocoAuth {

    template <typename ObjectPtrT>
    class ChocoAuthQObjectWrapper : public QObject {
        public:
            ChocoAuthQObjectWrapper(ObjectPtrT ptr){
                data = ptr;
            }
            ~ChocoAuthQObjectWrapper(){
                delete data;
            }
        private :
            ObjectPtrT data;
    };

}

#endif // ChocoAuth_QOBJECT_WRAPPER_H