/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Based on http://www.creativepulse.gr/en/blog/2014/restful-api-requests-using-qt-cpp-for-linux-mac-osx-ms-windows
 * By Alex Stylianos
 *
 **/

#ifndef ChocoAuth_HTTPREQUESTWORKER_H
#define ChocoAuth_HTTPREQUESTWORKER_H

#include <QObject>
#include <QString>
#include <QMap>
#include <QNetworkAccessManager>
#include <QNetworkReply>



namespace ChocoAuth {

enum ChocoAuthHttpRequestVarLayout {NOT_SET, ADDRESS, URL_ENCODED, MULTIPART};

class ChocoAuthHttpRequestInputFileElement {

public:
    QString variable_name;
    QString local_filename;
    QString request_filename;
    QString mime_type;

};


class ChocoAuthHttpRequestInput {

public:
    QString url_str;
    QString http_method;
    ChocoAuthHttpRequestVarLayout var_layout;
    QMap<QString, QString> vars;
    QMap<QString, QString> headers;
    QList<ChocoAuthHttpRequestInputFileElement> files;
    QByteArray request_body;

    ChocoAuthHttpRequestInput();
    ChocoAuthHttpRequestInput(QString v_url_str, QString v_http_method);
    void initialize();
    void add_var(QString key, QString value);
    void add_file(QString variable_name, QString local_filename, QString request_filename, QString mime_type);

};


class ChocoAuthHttpRequestWorker : public QObject {
    Q_OBJECT

public:
    QByteArray response;
    QNetworkReply::NetworkError error_type;
    QString error_str;

    explicit ChocoAuthHttpRequestWorker(QObject *parent = 0);
    virtual ~ChocoAuthHttpRequestWorker();

    QString http_attribute_encode(QString attribute_name, QString input);
    void execute(ChocoAuthHttpRequestInput *input);
    static QSslConfiguration* sslDefaultConfiguration;

signals:
    void on_execution_finished(ChocoAuthHttpRequestWorker *worker);

private:
    QNetworkAccessManager *manager;

private slots:
    void on_manager_finished(QNetworkReply *reply);

};

}

#endif // ChocoAuth_HTTPREQUESTWORKER_H
