/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ChocoAuthDefaultApi.h"
#include "ChocoAuthHelpers.h"
#include "ChocoAuthModelFactory.h"
#include "ChocoAuthQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace ChocoAuth {

ChocoAuthDefaultApi::ChocoAuthDefaultApi() {}

ChocoAuthDefaultApi::~ChocoAuthDefaultApi() {}

ChocoAuthDefaultApi::ChocoAuthDefaultApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
ChocoAuthDefaultApi::pingGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/ping");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "GET");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthDefaultApi::pingGetCallback);

    worker->execute(&input);
}

void
ChocoAuthDefaultApi::pingGetCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit pingGetSignal();
    } else {
        emit pingGetSignalE(error_type, error_str);
        emit pingGetSignalEFull(worker, error_type, error_str);
    }
}


}
