/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthAdminApi_H_
#define _ChocoAuth_ChocoAuthAdminApi_H_

#include "ChocoAuthHttpRequest.h"

#include "ChocoAuthErrorResponse.h"
#include "ChocoAuthUserInfo.h"
#include <QString>

#include <QObject>

namespace ChocoAuth {

class ChocoAuthAdminApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthAdminApi();
    ChocoAuthAdminApi(QString host, QString basePath);
    ~ChocoAuthAdminApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void deleteUser(QString* userid);
    void registerUser(ChocoAuthUserInfo& user);
    void updateUser(QString* userid, ChocoAuthUserInfo& user);
    
private:
    void deleteUserCallback (ChocoAuthHttpRequestWorker * worker);
    void registerUserCallback (ChocoAuthHttpRequestWorker * worker);
    void updateUserCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void deleteUserSignal();
    void registerUserSignal(ChocoAuthUserInfo* summary);
    void updateUserSignal(ChocoAuthUserInfo* summary);
    
    void deleteUserSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    void registerUserSignalE(ChocoAuthUserInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void updateUserSignalE(ChocoAuthUserInfo* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void deleteUserSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void registerUserSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void updateUserSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
