/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthErrorResponse.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthErrorResponse::ChocoAuthErrorResponse(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthErrorResponse::ChocoAuthErrorResponse() {
    init();
}

ChocoAuthErrorResponse::~ChocoAuthErrorResponse() {
    this->cleanup();
}

void
ChocoAuthErrorResponse::init() {
    message = new QString("");
    m_message_isSet = false;
    parameter_name = new QString("");
    m_parameter_name_isSet = false;
}

void
ChocoAuthErrorResponse::cleanup() {
    if(message != nullptr) { 
        delete message;
    }
    if(parameter_name != nullptr) { 
        delete parameter_name;
    }
}

ChocoAuthErrorResponse*
ChocoAuthErrorResponse::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthErrorResponse::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&message, pJson["message"], "QString", "QString");
    
    ::ChocoAuth::setValue(&parameter_name, pJson["parameterName"], "QString", "QString");
    
}

QString
ChocoAuthErrorResponse::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthErrorResponse::asJsonObject() {
    QJsonObject obj;
    if(message != nullptr && *message != QString("")){
        toJsonValue(QString("message"), message, obj, QString("QString"));
    }
    if(parameter_name != nullptr && *parameter_name != QString("")){
        toJsonValue(QString("parameterName"), parameter_name, obj, QString("QString"));
    }

    return obj;
}

QString*
ChocoAuthErrorResponse::getMessage() {
    return message;
}
void
ChocoAuthErrorResponse::setMessage(QString* message) {
    this->message = message;
    this->m_message_isSet = true;
}

QString*
ChocoAuthErrorResponse::getParameterName() {
    return parameter_name;
}
void
ChocoAuthErrorResponse::setParameterName(QString* parameter_name) {
    this->parameter_name = parameter_name;
    this->m_parameter_name_isSet = true;
}


bool
ChocoAuthErrorResponse::isSet(){
    bool isObjectUpdated = false;
    do{
        if(message != nullptr && *message != QString("")){ isObjectUpdated = true; break;}
        if(parameter_name != nullptr && *parameter_name != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

