/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ChocoAuthLoginApi.h"
#include "ChocoAuthHelpers.h"
#include "ChocoAuthModelFactory.h"
#include "ChocoAuthQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace ChocoAuth {

ChocoAuthLoginApi::ChocoAuthLoginApi() {}

ChocoAuthLoginApi::~ChocoAuthLoginApi() {}

ChocoAuthLoginApi::ChocoAuthLoginApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
ChocoAuthLoginApi::signDown(QString* sign_info) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/sign/down");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");




    if (sign_info != nullptr) {
        input.headers.insert("SignInfo", "sign_info");
    }

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthLoginApi::signDownCallback);

    worker->execute(&input);
}

void
ChocoAuthLoginApi::signDownCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit signDownSignal();
    } else {
        emit signDownSignalE(error_type, error_str);
        emit signDownSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthLoginApi::signIn(QString* sign_info) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/sign/in");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");




    if (sign_info != nullptr) {
        input.headers.insert("SignInfo", "sign_info");
    }

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthLoginApi::signInCallback);

    worker->execute(&input);
}

void
ChocoAuthLoginApi::signInCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthUserInfo* output = static_cast<ChocoAuthUserInfo*>(create(json, QString("ChocoAuthUserInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthUserInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit signInSignal(output);
    } else {
        emit signInSignalE(output, error_type, error_str);
        emit signInSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthLoginApi::signUp(QString* sign_info) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/sign/up");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");




    if (sign_info != nullptr) {
        input.headers.insert("SignInfo", "sign_info");
    }

    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthLoginApi::signUpCallback);

    worker->execute(&input);
}

void
ChocoAuthLoginApi::signUpCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthSignInfo* output = static_cast<ChocoAuthSignInfo*>(create(json, QString("ChocoAuthSignInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthSignInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit signUpSignal(output);
    } else {
        emit signUpSignalE(output, error_type, error_str);
        emit signUpSignalEFull(worker, error_type, error_str);
    }
}


}
