/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "ChocoAuthAdminApi.h"
#include "ChocoAuthHelpers.h"
#include "ChocoAuthModelFactory.h"
#include "ChocoAuthQObjectWrapper.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace ChocoAuth {

ChocoAuthAdminApi::ChocoAuthAdminApi() {}

ChocoAuthAdminApi::~ChocoAuthAdminApi() {}

ChocoAuthAdminApi::ChocoAuthAdminApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
ChocoAuthAdminApi::deleteUser(QString* userid) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/user/{userid}");

    QString useridPathParam("{"); useridPathParam.append("userid").append("}");
    fullPath.replace(useridPathParam, stringValue(userid));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "DELETE");





    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthAdminApi::deleteUserCallback);

    worker->execute(&input);
}

void
ChocoAuthAdminApi::deleteUserCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit deleteUserSignal();
    } else {
        emit deleteUserSignalE(error_type, error_str);
        emit deleteUserSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthAdminApi::registerUser(ChocoAuthUserInfo& user) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/user");



    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "PUT");


    
    QString output = user.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthAdminApi::registerUserCallback);

    worker->execute(&input);
}

void
ChocoAuthAdminApi::registerUserCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthUserInfo* output = static_cast<ChocoAuthUserInfo*>(create(json, QString("ChocoAuthUserInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthUserInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit registerUserSignal(output);
    } else {
        emit registerUserSignalE(output, error_type, error_str);
        emit registerUserSignalEFull(worker, error_type, error_str);
    }
}

void
ChocoAuthAdminApi::updateUser(QString* userid, ChocoAuthUserInfo& user) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/user/{userid}");

    QString useridPathParam("{"); useridPathParam.append("userid").append("}");
    fullPath.replace(useridPathParam, stringValue(userid));


    ChocoAuthHttpRequestWorker *worker = new ChocoAuthHttpRequestWorker();
    ChocoAuthHttpRequestInput input(fullPath, "POST");


    
    QString output = user.asJson();
    input.request_body.append(output);
    


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &ChocoAuthHttpRequestWorker::on_execution_finished,
            this,
            &ChocoAuthAdminApi::updateUserCallback);

    worker->execute(&input);
}

void
ChocoAuthAdminApi::updateUserCallback(ChocoAuthHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    QString json(worker->response);
    ChocoAuthUserInfo* output = static_cast<ChocoAuthUserInfo*>(create(json, QString("ChocoAuthUserInfo")));
    auto wrapper = new ChocoAuthQObjectWrapper<ChocoAuthUserInfo*> (output);
    wrapper->deleteLater();
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit updateUserSignal(output);
    } else {
        emit updateUserSignalE(output, error_type, error_str);
        emit updateUserSignalEFull(worker, error_type, error_str);
    }
}


}
