/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthSignInfo.h
 *
 * Information required for signing in and signin up a user 
 */

#ifndef ChocoAuthSignInfo_H_
#define ChocoAuthSignInfo_H_

#include <QJsonObject>


#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthSignInfo: public ChocoAuthObject {
public:
    ChocoAuthSignInfo();
    ChocoAuthSignInfo(QString json);
    ~ChocoAuthSignInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthSignInfo* fromJson(QString jsonString) override;

    QString* getEmail();
    void setEmail(QString* email);

    QString* getPassword();
    void setPassword(QString* password);


    virtual bool isSet() override;

private:
    QString* email;
    bool m_email_isSet;

    QString* password;
    bool m_password_isSet;

};

}

#endif /* ChocoAuthSignInfo_H_ */
