/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthAccessToken.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthAccessToken::ChocoAuthAccessToken(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthAccessToken::ChocoAuthAccessToken() {
    init();
}

ChocoAuthAccessToken::~ChocoAuthAccessToken() {
    this->cleanup();
}

void
ChocoAuthAccessToken::init() {
    access_token = new QString("");
    m_access_token_isSet = false;
    token_type = new QString("");
    m_token_type_isSet = false;
    user_info = new ChocoAuthUserInfo();
    m_user_info_isSet = false;
    redirect_uri = new QString("");
    m_redirect_uri_isSet = false;
    scope = new QList<ScopeEnum*>();
    m_scope_isSet = false;
    expiration_date = NULL;
    m_expiration_date_isSet = false;
}

void
ChocoAuthAccessToken::cleanup() {
    if(access_token != nullptr) { 
        delete access_token;
    }
    if(token_type != nullptr) { 
        delete token_type;
    }
    if(user_info != nullptr) { 
        delete user_info;
    }
    if(redirect_uri != nullptr) { 
        delete redirect_uri;
    }
    if(scope != nullptr) { 
        auto arr = scope;
        for(auto o: *arr) { 
            delete o;
        }
        delete scope;
    }
    if(expiration_date != nullptr) { 
        delete expiration_date;
    }
}

ChocoAuthAccessToken*
ChocoAuthAccessToken::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthAccessToken::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&access_token, pJson["access_token"], "QString", "QString");
    
    ::ChocoAuth::setValue(&token_type, pJson["token_type"], "QString", "QString");
    
    ::ChocoAuth::setValue(&user_info, pJson["user_info"], "ChocoAuthUserInfo", "ChocoAuthUserInfo");
    
    ::ChocoAuth::setValue(&redirect_uri, pJson["redirect_uri"], "QString", "QString");
    
    
    ::ChocoAuth::setValue(&scope, pJson["scope"], "QList", "QString");
    ::ChocoAuth::setValue(&expiration_date, pJson["expirationDate"], "QDateTime", "QDateTime");
    
}

QString
ChocoAuthAccessToken::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthAccessToken::asJsonObject() {
    QJsonObject obj;
    if(access_token != nullptr && *access_token != QString("")){
        toJsonValue(QString("access_token"), access_token, obj, QString("QString"));
    }
    if(token_type != nullptr && *token_type != QString("")){
        toJsonValue(QString("token_type"), token_type, obj, QString("QString"));
    }
    if((user_info != nullptr) && (user_info->isSet())){
        toJsonValue(QString("user_info"), user_info, obj, QString("ChocoAuthUserInfo"));
    }
    if(redirect_uri != nullptr && *redirect_uri != QString("")){
        toJsonValue(QString("redirect_uri"), redirect_uri, obj, QString("QString"));
    }
    if(scope->size() > 0){
        toJsonArray((QList<void*>*)scope, obj, "scope", "QString");
    }
    if(expiration_date != nullptr) { 
        toJsonValue(QString("expirationDate"), expiration_date, obj, QString("QDateTime"));
    }

    return obj;
}

QString*
ChocoAuthAccessToken::getAccessToken() {
    return access_token;
}
void
ChocoAuthAccessToken::setAccessToken(QString* access_token) {
    this->access_token = access_token;
    this->m_access_token_isSet = true;
}

QString*
ChocoAuthAccessToken::getTokenType() {
    return token_type;
}
void
ChocoAuthAccessToken::setTokenType(QString* token_type) {
    this->token_type = token_type;
    this->m_token_type_isSet = true;
}

ChocoAuthUserInfo*
ChocoAuthAccessToken::getUserInfo() {
    return user_info;
}
void
ChocoAuthAccessToken::setUserInfo(ChocoAuthUserInfo* user_info) {
    this->user_info = user_info;
    this->m_user_info_isSet = true;
}

QString*
ChocoAuthAccessToken::getRedirectUri() {
    return redirect_uri;
}
void
ChocoAuthAccessToken::setRedirectUri(QString* redirect_uri) {
    this->redirect_uri = redirect_uri;
    this->m_redirect_uri_isSet = true;
}

QList<QString*>*
ChocoAuthAccessToken::getScope() {
    return scope;
}
void
ChocoAuthAccessToken::setScope(QList<QString*>* scope) {
    this->scope = scope;
    this->m_scope_isSet = true;
}

QDateTime*
ChocoAuthAccessToken::getExpirationDate() {
    return expiration_date;
}
void
ChocoAuthAccessToken::setExpirationDate(QDateTime* expiration_date) {
    this->expiration_date = expiration_date;
    this->m_expiration_date_isSet = true;
}


bool
ChocoAuthAccessToken::isSet(){
    bool isObjectUpdated = false;
    do{
        if(access_token != nullptr && *access_token != QString("")){ isObjectUpdated = true; break;}
        if(token_type != nullptr && *token_type != QString("")){ isObjectUpdated = true; break;}
        if(user_info != nullptr && user_info->isSet()){ isObjectUpdated = true; break;}
        if(redirect_uri != nullptr && *redirect_uri != QString("")){ isObjectUpdated = true; break;}
        if(scope->size() > 0){ isObjectUpdated = true; break;}
        
    }while(false);
    return isObjectUpdated;
}
}

