/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthUserInfo.h
 *
 * 
 */

#ifndef ChocoAuthUserInfo_H_
#define ChocoAuthUserInfo_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthUserInfo: public ChocoAuthObject {
public:
    ChocoAuthUserInfo();
    ChocoAuthUserInfo(QString json);
    ~ChocoAuthUserInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthUserInfo* fromJson(QString jsonString) override;

    QString* getUserId();
    void setUserId(QString* user_id);

    QString* getEmail();
    void setEmail(QString* email);

    QList<QString*>* getVerification();
    void setVerification(QList<QString*>* verification);


    virtual bool isSet() override;

private:
    QString* user_id;
    bool m_user_id_isSet;

    QString* email;
    bool m_email_isSet;

    QList<QString*>* verification;
    bool m_verification_isSet;

};

}

#endif /* ChocoAuthUserInfo_H_ */
