/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthClientInfo.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthClientInfo::ChocoAuthClientInfo(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthClientInfo::ChocoAuthClientInfo() {
    init();
}

ChocoAuthClientInfo::~ChocoAuthClientInfo() {
    this->cleanup();
}

void
ChocoAuthClientInfo::init() {
    user_id = new QString("");
    m_user_id_isSet = false;
    client_id = new QString("");
    m_client_id_isSet = false;
    secret = new QString("");
    m_secret_isSet = false;
}

void
ChocoAuthClientInfo::cleanup() {
    if(user_id != nullptr) { 
        delete user_id;
    }
    if(client_id != nullptr) { 
        delete client_id;
    }
    if(secret != nullptr) { 
        delete secret;
    }
}

ChocoAuthClientInfo*
ChocoAuthClientInfo::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthClientInfo::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&user_id, pJson["userId"], "QString", "QString");
    
    ::ChocoAuth::setValue(&client_id, pJson["clientId"], "QString", "QString");
    
    ::ChocoAuth::setValue(&secret, pJson["secret"], "QString", "QString");
    
}

QString
ChocoAuthClientInfo::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthClientInfo::asJsonObject() {
    QJsonObject obj;
    if(user_id != nullptr && *user_id != QString("")){
        toJsonValue(QString("userId"), user_id, obj, QString("QString"));
    }
    if(client_id != nullptr && *client_id != QString("")){
        toJsonValue(QString("clientId"), client_id, obj, QString("QString"));
    }
    if(secret != nullptr && *secret != QString("")){
        toJsonValue(QString("secret"), secret, obj, QString("QString"));
    }

    return obj;
}

QString*
ChocoAuthClientInfo::getUserId() {
    return user_id;
}
void
ChocoAuthClientInfo::setUserId(QString* user_id) {
    this->user_id = user_id;
    this->m_user_id_isSet = true;
}

QString*
ChocoAuthClientInfo::getClientId() {
    return client_id;
}
void
ChocoAuthClientInfo::setClientId(QString* client_id) {
    this->client_id = client_id;
    this->m_client_id_isSet = true;
}

QString*
ChocoAuthClientInfo::getSecret() {
    return secret;
}
void
ChocoAuthClientInfo::setSecret(QString* secret) {
    this->secret = secret;
    this->m_secret_isSet = true;
}


bool
ChocoAuthClientInfo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(user_id != nullptr && *user_id != QString("")){ isObjectUpdated = true; break;}
        if(client_id != nullptr && *client_id != QString("")){ isObjectUpdated = true; break;}
        if(secret != nullptr && *secret != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

