/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _ChocoAuth_ChocoAuthDefaultApi_H_
#define _ChocoAuth_ChocoAuthDefaultApi_H_

#include "ChocoAuthHttpRequest.h"


#include <QObject>

namespace ChocoAuth {

class ChocoAuthDefaultApi: public QObject {
    Q_OBJECT

public:
    ChocoAuthDefaultApi();
    ChocoAuthDefaultApi(QString host, QString basePath);
    ~ChocoAuthDefaultApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void pingGet();
    
private:
    void pingGetCallback (ChocoAuthHttpRequestWorker * worker);
    
signals:
    void pingGetSignal();
    
    void pingGetSignalE(QNetworkReply::NetworkError error_type, QString& error_str);
    
    void pingGetSignalEFull(ChocoAuthHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
