/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthClientInfo.h
 *
 * Client is an identifier for an application that needs to use oauth2 authorization. This object  stores information about such client  
 */

#ifndef ChocoAuthClientInfo_H_
#define ChocoAuthClientInfo_H_

#include <QJsonObject>


#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthClientInfo: public ChocoAuthObject {
public:
    ChocoAuthClientInfo();
    ChocoAuthClientInfo(QString json);
    ~ChocoAuthClientInfo();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthClientInfo* fromJson(QString jsonString) override;

    QString* getUserId();
    void setUserId(QString* user_id);

    QString* getClientId();
    void setClientId(QString* client_id);

    QString* getSecret();
    void setSecret(QString* secret);


    virtual bool isSet() override;

private:
    QString* user_id;
    bool m_user_id_isSet;

    QString* client_id;
    bool m_client_id_isSet;

    QString* secret;
    bool m_secret_isSet;

};

}

#endif /* ChocoAuthClientInfo_H_ */
