/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "ChocoAuthAuthorizeRequest.h"

#include "ChocoAuthHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace ChocoAuth {

ChocoAuthAuthorizeRequest::ChocoAuthAuthorizeRequest(QString json) {
    init();
    this->fromJson(json);
}

ChocoAuthAuthorizeRequest::ChocoAuthAuthorizeRequest() {
    init();
}

ChocoAuthAuthorizeRequest::~ChocoAuthAuthorizeRequest() {
    this->cleanup();
}

void
ChocoAuthAuthorizeRequest::init() {
    response_type = new QString("");
    m_response_type_isSet = false;
    client_id = new QString("");
    m_client_id_isSet = false;
    redirect_uri = new QString("");
    m_redirect_uri_isSet = false;
    scope = new QList<ScopeEnum*>();
    m_scope_isSet = false;
    state = new QString("");
    m_state_isSet = false;
}

void
ChocoAuthAuthorizeRequest::cleanup() {
    if(response_type != nullptr) { 
        delete response_type;
    }
    if(client_id != nullptr) { 
        delete client_id;
    }
    if(redirect_uri != nullptr) { 
        delete redirect_uri;
    }
    if(scope != nullptr) { 
        auto arr = scope;
        for(auto o: *arr) { 
            delete o;
        }
        delete scope;
    }
    if(state != nullptr) { 
        delete state;
    }
}

ChocoAuthAuthorizeRequest*
ChocoAuthAuthorizeRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
ChocoAuthAuthorizeRequest::fromJsonObject(QJsonObject pJson) {
    ::ChocoAuth::setValue(&response_type, pJson["response_type"], "QString", "QString");
    
    ::ChocoAuth::setValue(&client_id, pJson["client_id"], "QString", "QString");
    
    ::ChocoAuth::setValue(&redirect_uri, pJson["redirect_uri"], "QString", "QString");
    
    
    ::ChocoAuth::setValue(&scope, pJson["scope"], "QList", "QString");
    ::ChocoAuth::setValue(&state, pJson["state"], "QString", "QString");
    
}

QString
ChocoAuthAuthorizeRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
ChocoAuthAuthorizeRequest::asJsonObject() {
    QJsonObject obj;
    if(response_type != nullptr && *response_type != QString("")){
        toJsonValue(QString("response_type"), response_type, obj, QString("QString"));
    }
    if(client_id != nullptr && *client_id != QString("")){
        toJsonValue(QString("client_id"), client_id, obj, QString("QString"));
    }
    if(redirect_uri != nullptr && *redirect_uri != QString("")){
        toJsonValue(QString("redirect_uri"), redirect_uri, obj, QString("QString"));
    }
    if(scope->size() > 0){
        toJsonArray((QList<void*>*)scope, obj, "scope", "QString");
    }
    if(state != nullptr && *state != QString("")){
        toJsonValue(QString("state"), state, obj, QString("QString"));
    }

    return obj;
}

QString*
ChocoAuthAuthorizeRequest::getResponseType() {
    return response_type;
}
void
ChocoAuthAuthorizeRequest::setResponseType(QString* response_type) {
    this->response_type = response_type;
    this->m_response_type_isSet = true;
}

QString*
ChocoAuthAuthorizeRequest::getClientId() {
    return client_id;
}
void
ChocoAuthAuthorizeRequest::setClientId(QString* client_id) {
    this->client_id = client_id;
    this->m_client_id_isSet = true;
}

QString*
ChocoAuthAuthorizeRequest::getRedirectUri() {
    return redirect_uri;
}
void
ChocoAuthAuthorizeRequest::setRedirectUri(QString* redirect_uri) {
    this->redirect_uri = redirect_uri;
    this->m_redirect_uri_isSet = true;
}

QList<QString*>*
ChocoAuthAuthorizeRequest::getScope() {
    return scope;
}
void
ChocoAuthAuthorizeRequest::setScope(QList<QString*>* scope) {
    this->scope = scope;
    this->m_scope_isSet = true;
}

QString*
ChocoAuthAuthorizeRequest::getState() {
    return state;
}
void
ChocoAuthAuthorizeRequest::setState(QString* state) {
    this->state = state;
    this->m_state_isSet = true;
}


bool
ChocoAuthAuthorizeRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(response_type != nullptr && *response_type != QString("")){ isObjectUpdated = true; break;}
        if(client_id != nullptr && *client_id != QString("")){ isObjectUpdated = true; break;}
        if(redirect_uri != nullptr && *redirect_uri != QString("")){ isObjectUpdated = true; break;}
        if(scope->size() > 0){ isObjectUpdated = true; break;}
        if(state != nullptr && *state != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

