/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthAccessToken.h
 *
 * 
 */

#ifndef ChocoAuthAccessToken_H_
#define ChocoAuthAccessToken_H_

#include <QJsonObject>


#include "ChocoAuthUserInfo.h"
#include <QDateTime>
#include <QList>
#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthAccessToken: public ChocoAuthObject {
public:
    ChocoAuthAccessToken();
    ChocoAuthAccessToken(QString json);
    ~ChocoAuthAccessToken();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthAccessToken* fromJson(QString jsonString) override;

    QString* getAccessToken();
    void setAccessToken(QString* access_token);

    QString* getTokenType();
    void setTokenType(QString* token_type);

    ChocoAuthUserInfo* getUserInfo();
    void setUserInfo(ChocoAuthUserInfo* user_info);

    QString* getRedirectUri();
    void setRedirectUri(QString* redirect_uri);

    QList<QString*>* getScope();
    void setScope(QList<QString*>* scope);

    QDateTime* getExpirationDate();
    void setExpirationDate(QDateTime* expiration_date);


    virtual bool isSet() override;

private:
    QString* access_token;
    bool m_access_token_isSet;

    QString* token_type;
    bool m_token_type_isSet;

    ChocoAuthUserInfo* user_info;
    bool m_user_info_isSet;

    QString* redirect_uri;
    bool m_redirect_uri_isSet;

    QList<QString*>* scope;
    bool m_scope_isSet;

    QDateTime* expiration_date;
    bool m_expiration_date_isSet;

};

}

#endif /* ChocoAuthAccessToken_H_ */
