/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthAuthorizeRequest.h
 *
 * 
 */

#ifndef ChocoAuthAuthorizeRequest_H_
#define ChocoAuthAuthorizeRequest_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthAuthorizeRequest: public ChocoAuthObject {
public:
    ChocoAuthAuthorizeRequest();
    ChocoAuthAuthorizeRequest(QString json);
    ~ChocoAuthAuthorizeRequest();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthAuthorizeRequest* fromJson(QString jsonString) override;

    QString* getResponseType();
    void setResponseType(QString* response_type);

    QString* getClientId();
    void setClientId(QString* client_id);

    QString* getRedirectUri();
    void setRedirectUri(QString* redirect_uri);

    QList<QString*>* getScope();
    void setScope(QList<QString*>* scope);

    QString* getState();
    void setState(QString* state);


    virtual bool isSet() override;

private:
    QString* response_type;
    bool m_response_type_isSet;

    QString* client_id;
    bool m_client_id_isSet;

    QString* redirect_uri;
    bool m_redirect_uri_isSet;

    QList<QString*>* scope;
    bool m_scope_isSet;

    QString* state;
    bool m_state_isSet;

};

}

#endif /* ChocoAuthAuthorizeRequest_H_ */
