/**
 * Choco Authorization API
 * This is an interface for authorization by using ChocoAuth service   
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChocoAuthErrorResponse.h
 *
 * 
 */

#ifndef ChocoAuthErrorResponse_H_
#define ChocoAuthErrorResponse_H_

#include <QJsonObject>


#include <QString>

#include "ChocoAuthObject.h"

namespace ChocoAuth {

class ChocoAuthErrorResponse: public ChocoAuthObject {
public:
    ChocoAuthErrorResponse();
    ChocoAuthErrorResponse(QString json);
    ~ChocoAuthErrorResponse();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    ChocoAuthErrorResponse* fromJson(QString jsonString) override;

    QString* getMessage();
    void setMessage(QString* message);

    QString* getParameterName();
    void setParameterName(QString* parameter_name);


    virtual bool isSet() override;

private:
    QString* message;
    bool m_message_isSet;

    QString* parameter_name;
    bool m_parameter_name_isSet;

};

}

#endif /* ChocoAuthErrorResponse_H_ */
